title: Applied Algebra Day 2025
theme: minima
description: University of Wisconsin-Madison, July 18-20, 2025
head:
  custom: |
    <script>
      window.MathJax = {
        tex: {
          inlineMath: [['$', '$']],
          displayMath: [['$$', '$$']]
        }
      };
    </script>
    <script defer src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script>
